---
openapi: 3.0.3
info:
  title: Console Task App API
  version: 1.0.0
  description: API for console-based task management application

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve the list of all tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Create a new task
      description: Add a new task to the task list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input

  /tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve details of a specific task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

    put:
      summary: Update a task
      description: Update the details of an existing task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

    delete:
      summary: Delete a task
      description: Remove a task from the task list
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found

  /tasks/{id}/toggle:
    patch:
      summary: Toggle task completion status
      description: Toggle the completion status of a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Description of the task
        completed:
          type: boolean
          description: Whether the task is completed
      required:
        - id
        - title
        - completed

    TaskInput:
      type: object
      properties:
        title:
          type: string
          description: Title of the task (required)
        description:
          type: string
          description: Description of the task (optional)
      required:
        - title

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Updated title of the task (optional)
        description:
          type: string
          description: Updated description of the task (optional)